ALTER TABLE orders ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE delivery_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id),
    delivery_partner_id BIGINT NOT NULL REFERENCES delivery_partners(id),
    version BIGINT NOT NULL DEFAULT 0,
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_delivery_assignment_order UNIQUE (order_id)
);

CREATE INDEX idx_delivery_assignments_partner_id ON delivery_assignments(delivery_partner_id);
