CREATE TABLE rating_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    customer_id BIGINT NOT NULL REFERENCES users(id),
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_rating_review_order_customer UNIQUE (order_id, customer_id)
);

CREATE INDEX idx_rating_reviews_order_id ON rating_reviews(order_id);
CREATE INDEX idx_rating_reviews_customer_id ON rating_reviews(customer_id);
