CREATE TABLE delivery_partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    city VARCHAR(100) NOT NULL
);

CREATE INDEX idx_delivery_partners_city ON delivery_partners(city);
